### ISSUE TITLE
running clandmark in windows

### ISSUE THREAD

**Issue by arthahir** [uricamic/clandmark#13]
hi,
     how  can i run clandmakr in windows ?
 please help me...i have downloaded clandmark_master file
what is the first thing i need to do in windows?

**Comment by uricamic** [comment]
Hi @arthahir.

first you need to compile it. You will need CMake and for example MS Visual Studio for that (CMake can generate project for MS Visual Studio). I will describe the process on CLandmark webpage when I get access to windows machine.

**Comment by arthahir** [comment]
hi uricam
               so i need Cmake for generating project to be run in MS visual studio..
how can i go cmake in order to generate?? 
there is another dout? which version of  MS visual studio is best to use clandmark?

**Comment by uricamic** [comment]
Hi, 

yep, CLandmark configuration & compilation is maintained by CMake, so you should use it (it has quite nice Qt GUI on windows platform). The CMake process is quite easy, basically, you just specify source and build directory, hit configure and if needed change some variables that are listed in the GUI. 

I was using Visual Studio 2008 Professional for quite a long time, then I abandoned windows, so I cannot give you proper advice on that. However, last time I tried to compile CLandmark under windows, I used Visual Studio 2013 and it also did the job.

**Comment by uricamic** [comment]
Closing. There are now build scripts ready for windows OS.
