### ISSUE TITLE
Linux system error while example enabled

### ISSUE THREAD

**Issue by chocobrownie** [uricamic/clandmark#14]
Hi there,

I am a new coder and I have been trying to get this library work for a week. Since it has Linux installation instruction, I even installed Linux for it.

Following the instructions I have made the compilation, however in the Linux installation tutorial, it disabled the example code generation, which means I still need to figure a way to compile a perfectly linked file. Not knowing how I tried to enable the example code cmake generation by turning it on, however it results in error during "make" step. My Cmake is 3.0.2 and to fit your program my opencv is 2.4.10.

I will greatly appreciate it if the problem can be solved or there are alternatives, I'm pasting the error message part below.

Linking CXX shared library libflandmark.so
[ 88%] Built target flandmark
Scanning dependencies of target static_input
[ 94%] Building CXX object examples/CMakeFiles/static_input.dir/static_input.cpp.o
make[2]: **\* No rule to make target '/usr/share/opencv/lib/libopencv_videostab.so.2.4.11', needed by 'examples/static_input'.  Stop.
CMakeFiles/Makefile2:165: recipe for target 'examples/CMakeFiles/static_input.dir/all' failed
make[1]: **\* [examples/CMakeFiles/static_input.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2

Thanks!

**Comment by uricamic** [comment]
Hi, 

from the error message it seems that the problem is with OpenCV not with the examples itself. 
I will check it tomorrow, maybe there is just something missing. 

I wanted to update installation instructions and submit the learning scripts for MATLAB soon, but unfortunately I got some work to do with higher priority, so sorry for the inconvenience.

**Comment by chocobrownie** [comment]
Sure, I'll wait and see if we could figure this out. I have been using the same version of opencv as you are, if they have bug, I guess they will also appear to be the same but I'm not sure.

Yes, I have modified and tried Matlab code you posted, I changed the ".." to the folder that's been working, corrected the opencv version from 2.3 to 2.4 (minority), downloaded microsoft sdk 8 for Mex (I'm using windows 8.1 and windows 10 soon this month). But the system get stuck on the core code, which eval. It only says cannot install successfully so I'm not sure what is wrong.

Hopefully this info also helps b4 you post the matlab code. And after you finish your current work, let's try to figure out the C++ code :)

Thanks!

**Comment by uricamic** [comment]
Hi @chocobrownie, 

I made a small change to the examples/CMakeLists.txt which should solve your problem. It forces examples to link just to the necessary libraries from OpenCV (videostab is not one of them). 

Please report, if it really works. 

However, if you need to use this particular library (videostab), then you should fix your OpenCV build.
