### ISSUE TITLE
how to recognize half face ?

### ISSUE THREAD

**Issue by bezita** [uricamic/clandmark#18]
thank u for this great job.
I compiled this project and run the 'static_input', fount it can not recoginze the half face like the demo pic in your website(http://cmp.felk.cvut.cz/~uricamic/clandmark/images/profile_faces.png), how should i do to recognize the half face?
![ttt](https://cloud.githubusercontent.com/assets/4016637/9575969/559528be-5006-11e5-8b25-25557375d9af.jpg)

**Comment by uricamic** [comment]
Hi @bezita, 

from the enclosed picture I see that the 8 landmark model is fitted. 

If you would like to detect landmarks on profile faces you should either use the corresponding model from multiview models (see http://cmp.felk.cvut.cz/~uricamic/clandmark/#downloads-learned-models) or if you would like to detect both landmarks and the view the joint multi-view landmark detector (see the code snippet: http://cmp.felk.cvut.cz/~uricamic/clandmark/#snippets-mv). 

I am currently updating the webpages, there will be new learned models updated soon. I will also try to create new completely self-contained C++ example with the joint multi-view detector.

**Comment by bezita** [comment]
Hi @uricamic 

I tried the "joint_mv_models", and these models work well when i choosed the match one.
After read the  "Joint multi-view facial landmark detector snippets",however, i have no idea to use this snippet in my projects.

I'm so glad that you said  " I will also try to create new completely self-contained C++ example with the joint multi-view detector.'', I'll be right here waiting for you :+1:  , thank u again !
