### ISSUE TITLE
Not understanding what bbox is

### ISSUE THREAD

**Issue by RafaRuiz** [uricamic/clandmark#20]
Hello, I've seen an example, for example the examples/video_input.cpp and I can see this when passing from `cv::Rect` (face_rect) to `bbox`:
        bbox[0] = faces[i].x;
        bbox[1] = faces[i].y;
        bbox[2] = faces[i].x + faces[i].width;
        bbox[3] = faces[i].y;
        bbox[4] = faces[i].x + faces[i].width;
        bbox[5] = faces[i].y + faces[i].height;
        bbox[6] = faces[i].x;
        bbox[7] = faces[i].y + faces[i].height;

the parameter 0 and 6 is the same, the parameter 1 and 3 is the same, 2 and 4, 5 and 7. 

Why?

**Comment by uricamic** [comment]
Hi @RafaRuiz,

CLandmark supports a general face box given by coordinates of all its corners. However, most of the face detectors (including the OpenCV one used in the example) provide only axis aligned face boxes. That's why some of the coordinates seem to be duplicates.

**Comment by RafaRuiz** [comment]
Fair enough, thank you very much!

**Comment by uricamic** [comment]
No problem, I am glad it helped.
