### ISSUE TITLE
how can i get the "dense set of landmark" 

### ISSUE THREAD

**Issue by NanYoMy** [uricamic/clandmark#22]
clandmark is brilliant job, i want to known, if i want to get the result with dense set of landmark, how can i do it

**Comment by uricamic** [comment]
Hi @NanYoMy, 

the learned models for the 68 landmarks set is going to be published soon. 
The learning scripts for MATLAB which enable the possibility to learn arbitrary configuration of landmarks as well.

**Comment by NanYoMy** [comment]
ok, i am waiting for it!
