### ISSUE TITLE
Inconsistency detected error while ccmake

### ISSUE THREAD

**Issue by HDaoud** [uricamic/clandmark#28]
Hi,

trying to ccmake the package, I got the following error.

 Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!

Regards,
Hayyan

**Comment by uricamic** [comment]
Hi @HDaoud, 

could you please specify your system and steps you did which led to this error message?

**Comment by HDaoud** [comment]
I'm using Ubuntu 14.04, downloaded the zip file from github and followed the steps in "http://cmp.felk.cvut.cz/~uricamic/clandmark/#installation".
after typing the "CCMake .." it gives the error.

**Comment by uricamic** [comment]
And is CMake working for you on some other projects? 

I am also using Ubuntu 14.04 and I have never encountered anything similar. I have found some link for 15.04, where they claim reinstalling libcurl3 to help: http://ubuntuforums.org/showthread.php?t=2277164

**Comment by HDaoud** [comment]
Yup, Cmake is working fine, I also tried to do CMake and got the same error, I will look into the link you've sent and update you.
Thanks

**Comment by uricamic** [comment]
I found another one which might be also useful:
https://forum.directadmin.com/showthread.php?t=51343

**Comment by HDaoud** [comment]
Yeah I read that,

and here is another one, http://stackoverflow.com/questions/20007961/error-running-a-compiled-c-file-uses-opengl-error-inconsistency-detected

I have nvidia as well, what is yours?

**Comment by HDaoud** [comment]
Hi Solved following: http://www.cfd-online.com/Forums/openfoam-installation/136477-inconsistency-detected-ld-so-2-3-0-ubuntu-14-04-a.html

I added the following command in the file ~/.bashrc :
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1

**Comment by uricamic** [comment]
Hi, 

ok. Thanks for the message.
