### ISSUE TITLE
Trying to run the example, what am I doing wrong?

### ISSUE THREAD

**Issue by HDaoud** [uricamic/clandmark#29]
Hi Michal,

I'm tying to run the example, and I'm getting this error:

```
$:~/clandmark/build/examples$ ./static_input 
Usage: static_input <path_to_haarcascade> <flandmark_model.xml> <input_image> [<output_image>]
```

_feeding the parameters in the suggested order:_

```
$:~/clandmark/build/examples$ ./static_input ./haarcascade_frontalface_alt.xml ./flandmark_model.xml ./face.jpg
Flandmark model loaded in 16.5043 ms
--(!)Error loading
```

**Comment by HDaoud** [comment]
Ok, my bad, looking at code, you don't have to put the name of the haarcascade xml file, only the directory as it's done in the code.

**Comment by uricamic** [comment]
Yes, sorry for that. 
I should unify the examples and create some documentation for them.

**Comment by HDaoud** [comment]
Thank you Michal, documentation will be of a great help, I'm currently installing the flandmark as I am working with C (IplImage...) I see that the new Clandmark use the Mat, vectors and it's OOP based, is there a way to use it with C? or should I use flandmark?
Thanks again!

**Comment by uricamic** [comment]
Hi @HDaoud, 

`CLandmark` is object oriented. However, I think you can use it in C as well (actually, the MATLAB interface is doing exactly that). 
Moreover, I think that `IplImage` is considered to be obsolete in OpenCV and `cv::Mat` is more convenient to use in my humble opinion. 

`flandmark` is of course also possible to be used, but we do not work on it anymore. So, it is limited to detect only those 8 predefined landmarks and it seems that the possibility to save newly trained model is now broken.

**Comment by HDaoud** [comment]
Thanks for the reply, I will dig more in CLandmark while the documentation is prepared ;)
