### ISSUE TITLE
Negative out-of-bounds access in CTreeMaxSumSolver::dt1D

### ISSUE THREAD

**Issue by ashbash1987** [uricamic/clandmark#3]
Hi,

I've just been trying to integrate CLandmark into a face detection app, pretty much following the example code (with some additional code from OpenCV to be able to process data from an iPad camera input source), and unfortunately it all comes to a halt when running through `CTreeMaxSumSolver::dt1D(...)` while in the following loop:

``` cpp
while (s <= z[k])
    k--;
    s = ((src[q*step] - src[v[k]*step]) - b*(q - v[k]) + a*(square(q) - square(v[k]))) / (2*a*(q-v[k]));
}
```

The reason for the halt is because `s` has become -Infinity, causing `k` to become negative.

This is using code as of latest in master (315c1e4b88).

**Comment by uricamic** [comment]
Hi, 

could you please provide me the model, which you are using? Because I haven't encountered any problems using many different models yet. 
However, I admit, that there are no fail-safe mechanisms in some parts of the code. In this case, I think it depends on the method chosen for learning the model, which has to enforce some conditions on the weight vector.

**Comment by ashbash1987** [comment]
Thanks for the quick response back. I'm using the provided `flandmark_model.xml` file in the data folder.

**Comment by uricamic** [comment]
I see, that should be the problem. I am still polishing some parts of the code to publish and I forgot to mention that this model is not suitable for usage with distance transform. It is some old version which replaces the previous library - flandmark. 

I will try to upload more models soon. Sorry for the inconvenience.

**Comment by ashbash1987** [comment]
Ok, thanks for letting me know. I've just swapped to using the `8Lfrontal_SPLIT_1_init.xml` model, and that looks to be working much much better!

**Comment by uricamic** [comment]
That one should work with the code, but I am afraid it won't detect anything, since it does not contain the learned weight vector w. 

I will try to upload some of the learned models I have as soon as possible.

**Comment by lizhong323** [comment]
Hello uricamic,

I have encounter same problem with ashbash1987, when I replace the xml file to 8Lfrontal_SPLIT_1_init.xml, the program could run smoothly but the result is not accurate at all.

I pretty much follow the static_input example, you said you haven't encountered any problems using many different models yet. Could you give me some hint about how to detect the point accurately?

BTW, I have successfully detect 7 face feature points use old library flandmark, but looks the new library still only could only detect 7 face feature points, could you also give me some instruction about how to generate more points like your webpage post? 

Thanks!

**Comment by uricamic** [comment]
Hi @lizhong323, 

the 8Lfrontal_SPLIT_1_init.xml is an init file, which should be used for learning, i.e. it does not contain the learned weight vector. It cannot actually detect anything. 

I have uploaded some models (e.g. the multi-view variant detecting 21, 19 or 13 landmarks depending on the yaw angle estimate) which can be used on the project webpage and I will upload some more soon. 
It is also possible to use the enclosed 8 landmark model, which replaces the flandmark. However, so far there is just the version, which does not use speed ups for features computation and distance transform. So the initialization of Flandmark class and detection call looks a bit different. I will write about these differences on the webpage as well. 

I am finalizing the MATLAB scripts for learning user-defined models when it is finished, I will write a tutorial on the webpage how to define new model and how to learn it from annotated data. It will be only for MATLAB for start, however after fixing the Python interface I would like to prepare the learning scripts for Python as well.

**Comment by lizhong323** [comment]
Hi uricamic,

Thank you for your swift reply!
Yes, I just try two zip file which contain the learned models, it could detect more landmarks, but the result seems not accurate. I just follow the C++ static_input example, do I follow the right example?

I use the face.jpg in data folder. And use this learned model:INDIVIDUAL_FRONTAL_AFLW_SPLIT_1.xml, could give me some hint to fix it?
![20150620155143](https://cloud.githubusercontent.com/assets/4120723/8269170/f19a9f40-1763-11e5-8a94-d0d088c90a17.png)

**Comment by uricamic** [comment]
Hi @lizhong323,

could you please provide me more information about this issue? Which operating system are you using and what version of OpenCV to compile static_input.cpp? And have you done any modifications to the code? 

I have just tried to call static_input example with model: INDIVIDUAL_FRONTAL_AFLW_SPLIT_1.xml as flandmark model on face.jpg and I get quite nice output:

![flandmark - static input demo_012](https://cloud.githubusercontent.com/assets/1597574/8271073/729b56c6-1803-11e5-99c3-d2f40c7c7c20.png)

**Comment by lizhong323** [comment]
Hello Michal,

Thank you for your kind reply!

I compile my program using VS2013 in Win 8.1, and the opencv version is
kind old (2.4.9), but still ok I believe.
I using my own face detector class(DFace) implement by opencv which return
the top left and bottom right pixel position of the faces.
I did some revision, but I think basicly follow your example, could you
help me check my code if it is convenient for you?
The code is attached.
Thanks for your patient!


   1. #include <opencv2/objdetect/objdetect.hpp>
   2. #include <opencv2/highgui/highgui.hpp>
   3. #include <opencv2/imgproc/imgproc.hpp>
   4. #include "CImg.h"
   5. #include <iostream>
   6. #include <iomanip>
   7. #include <stdio.h>
   8. #include "DFace.h"
   9. #include "Flandmark.h"
   10. #include "CFeaturePool.h"
   11. #include "CSparseLBPFeatures.h"
   12. #include "helpers.h"
   13.
   14. #define SHOW_WINDOWS
   15.
   16. using namespace std;
   17. using namespace cv;
   18. using namespace clandmark;
   19.
   20. /** Global variables */
   21. //String face_cascade_name = "lbpcascade_frontalface.xml";
   22. String face_cascade_name = "haarcascade_frontalface_alt.xml";
   23. CascadeClassifier face_cascade;
   24. string window_name = "flandmark - static input demo";
   25. RNG rng(12345);
   26.
   27. cimg_library::CImg<unsigned char> * cvImgToCImg(cv::Mat &cvImg)
   28. {
   29.     cimg_library::CImg<unsigned char> * result = new
    cimg_library::CImg<unsigned char>(cvImg.cols, cvImg.rows);
   30.
   31.     for (int x = 0; x < cvImg.cols; ++x)
   32.         for (int y = 0; y < cvImg.rows; ++y)
   33.             (*result)(x, y) = cvImg.at<uchar>(y, x);
   34.
   35.     return result;
   36. }
   37.
   38. cv::Mat & CImgtoCvImg(cv::Mat &result, cimg_library::CImg<unsigned
   char> *img)
   39. {
   40.     result = cv::Mat(img->height(), img->width(), CV_8U);
   41.
   42.     for (int x = 0; x < result.cols; ++x)
   43.         for (int y = 0; y < result.rows; ++y)
   44.             result.at<uchar>(y, x) = (*img)(x, y);
   45.
   46.     return result;
   47. }
   48.
   49. /** @function main */
   50. int main(int argc, const char** argv)
   51. {
   52.
   53. //  Mat frame = imread("face.jpg");
   54.
   55.     Mat frame = imread("Aaron_Eckhart_0001.jpg");
   56.
   57.
   58.     DFace face(frame);
   59.
   60.
   //Flandmark *flandmark =
Flandmark::getInstanceOf("8Lfrontal_SPLIT_1_init.xml");

   61.
   //Flandmark *flandmark = Flandmark::getInstanceOf("flandmark_model.xml");

   62.
   //Flandmark *flandmark =
Flandmark::getInstanceOf("xmlone/JOINT_MV_AFLW_SPLIT_1_-profile.xml");

   63.     Flandmark *flandmark = Flandmark::getInstanceOf(
   "xmltwo/INDIVIDUAL_FRONTAL_AFLW_SPLIT_1.xml");
   64.
   //  Flandmark *flandmark =
Flandmark::getInstanceOf("xmlone/JOINT_MV_AFLW_SPLIT_1_frontal.xml");

   65.     if (!flandmark)
   66.     {
   67.         cerr <<
   "Usage: static_input <flandmark_model.xml> <input_image> [<output_image>]"
    << endl;
   68.         return -1;
   69.     }
   70.
   71.     CFeaturePool *featurePool = new
    CFeaturePool(flandmark->getBaseWindowSize()[0],
flandmark->getBaseWindowSize()[1]);
   72.     featurePool->addFeaturesToPool(
   73.         new CSparseLBPFeatures(
   74.         featurePool->getWidth(),
   75.         featurePool->getHeight(),
   76.         featurePool->getPyramidLevels(),
   77.         featurePool->getCumulativeWidths()
   78.         )
   79.         );
   80.
   81.     flandmark->setNFfeaturesPool(featurePool);
   82.
   83.     Mat frame_gray;
   84.     int bbox[8];
   85.     fl_double_t *landmarks;
   86.
   87.     cvtColor(frame, frame_gray, CV_BGR2GRAY);
   88.     equalizeHist(frame_gray, frame_gray);
   89.
   90.     bbox[0] = face.X1;
   91.     bbox[1] = face.Y1;
   92.
   93.     bbox[2] = face.X2;
   94.     bbox[3] = face.Y1;
   95.
   96.     bbox[4] = face.X2;
   97.     bbox[5] = face.Y2;
   98.
   99.     bbox[6] = face.X1;
   100.     bbox[7] = face.Y2;
   101.
   102.     imshow("test", frame_gray);
   103.     waitKey(1);
   104.
   105.     // Detect facial landmarks
   106.     cimg_library::CImg<unsigned char
   >* frm_gray = cvImgToCImg(frame_gray);
   107.     //      flandmark->detect_from_nf(frm_gray, bbox);
   108.     //      flandmark->detect( frm_gray, bbox );
   109.     flandmark->detect_optimized(frm_gray, bbox);
   110.
   111.     delete frm_gray;
   112.
   113.     // Get detected landmarks
   114.     landmarks = flandmark->getLandmarks();
   115.
   116.     // Draw bounding box and detected landmarks
   117.
       rectangle(frame, Point(bbox[0], bbox[1]), Point(bbox[4],
bbox[5]), Scalar(255, 0, 0));
   118.     circle(frame, Point(int(landmarks[0]), int
   (landmarks[1])), 2, Scalar(255, 0, 0), -1);
   119.     for (int
    i = 2; i < 2 * flandmark->getLandmarksCount(); i += 2)
   120.     {
   121.         circle(frame, Point(int(landmarks[i]), int
   (landmarks[i + 1])), 2, Scalar(0, 0, 255), -1);
   122.     }
   123.
   124.     // Textual output
   125.     printTimingStats(flandmark->timings);
   126.     printLandmarks(landmarks, flandmark->getLandmarksCount());
   127.
       printLandmarks(flandmark->getLandmarksNF(),
flandmark->getLandmarksCount());
   128.
   129.     imshow(window_name, frame);
   130.
   131.     cv::waitKey(0);
   132.
   133.     return 0;
   134. }



Regards,

Zhong











On Sun, Jun 21, 2015 at 3:58 AM, Michal Uřičář <notifications@github.com>
wrote:

> Hi @lizhong323 <https://github.com/lizhong323>,
>
> could you please provide me more information about this issue? Which
> operating system are you using and what version of OpenCV to compile
> static_input.cpp? And have you done any modifications to the code?
>
> I have just tried to call static_input example with model:
> INDIVIDUAL_FRONTAL_AFLW_SPLIT_1.xml as flandmark model on face.jpg and I
> get quite nice output:
>
> [image: flandmark - static input demo_012]
> <https://cloud.githubusercontent.com/assets/1597574/8271073/729b56c6-1803-11e5-99c3-d2f40c7c7c20.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uricamic/clandmark/issues/3#issuecomment-113878897>.
>



-- 

Regards,

Zhong Li

Department of Computer Science & IT, University of Missouri-Columbia

Email: zlx93@mail.missouri.edu
