### ISSUE TITLE
Rotation Tolerance

### ISSUE THREAD

**Issue by HDaoud** [uricamic/clandmark#37]
Hi Michal!

I have implemented Clandmark on a video stream, however, I noticed the following compared to Flandmark:

1- False positive rate is better, but still high, areas of white floor, or drawers always detected as a face!
2- Rotation tolerance, the Clandmark seems not to detect faces after certain rotation, to check on that, I used the provided image example, and ran the static program on the flipped version, no detection :(!
below is the results of the normal and flipped view
[http://postimg.org/image/5yqi37zlh/]

In one of your replies you mentioned that you were training a new model that is tolerated to rotation and yaw, is it done? do you have better models to be used, with better F measure (recall/precision).

Thanks!
Hayyan 

PS: is the messages of "opengl support available" and "init done" from imshow or from the code? I couldn't find their source -_-'

**Comment by uricamic** [comment]
Hi @HDaoud, 

both problems you mention are actually not related to the CLandmark itself, but to the face detector, which is used to detect faces prior to detect the landmarks. CLandmark expects the face boxes on its input and all the models that are provided so far will always output landmarks on any input provided, i.e. there is no check if the box provided contained face or not. 

The common approach to detect rotated faces is to rotate the image before the face detection (or to detect faces on several rotations).  
We usually use the commercial face detector (http://www.eyedea.cz/), but you can use arbitrary one. 
I heard that the OpenCV haarcascade can provide much better results, when it is retrained on better data.

**Comment by HDaoud** [comment]
Thanks for your quick reply!

I need to use Clandmark in my research, I don't know if I can use the commercial detector, maybe if it has publication that I can refer to.

I didn't get your suggestion regarding OpenCV, should I retrain a haarcascade before using with Clandmark? or should I use the openCV?

Thanks!

**Comment by uricamic** [comment]
The OpenCV haarcascade can be trained on your data, so the idea is to retrain it on some standard database of faces, which is in some sense better than what they used for training. 

The commercial detector which we use (not in the publicly available codes, though) is an implementation of this [paper](http://cmp.felk.cvut.cz/~matas/papers/sochman-waldboost-cvpr05.pdf).

**Comment by HDaoud** [comment]
Noted!

Thanks for your input.

Regards,
