### ISSUE TITLE
There is an Version already compiled ?

### ISSUE THREAD

**Issue by henriquem** [uricamic/clandmark#4]
Hello @uricamic ,

I'm anxious to use clandmark !! but I dont know how works language C++ , I'm working with Java,
and at the moment I use is flandmark provided by bytecode-presents ( an version JNI for JAVA ) 

Do you have estimate, when will release with support JNI ?

Another question: There is some version compiled from cflandmark ?

Thanks so much !

**Comment by uricamic** [comment]
Hi, 

the Java interface has a lower priority for me than Python interface. If I will find some nice tutorial about JNI, I will create it as well.

I can provide compiled version for linux and windows now (both 64bit).

**Comment by henriquem** [comment]
what a pity!
It could help so much the world java :'(

**Comment by saudet** [comment]
FYI, it should be pretty easy to create a Java interface with JavaCPP:
https://github.com/bytedeco/javacpp-presets/issues/69

**Comment by uricamic** [comment]
Hi @saudet, 

thanks for the link, I will try that.

**Comment by henriquem** [comment]
The bytedeco javacpp-presets / provides flandmark ( old version ) 
We anxious to see The exciting clandmark in java wrapper !!! 
Uricamic, do you know some estimates done new version java .... ?
Thks a lot!

**Comment by uricamic** [comment]
@henriquem 
Hard to say, I am now busy with some projects and the first item on the TODO list for CLandmark is polishing and publishing the learning scripts (MATLAB and hopefully also Python). 

If the Java wrapper will be as easy as MATLAB or Python, then it might be soon. Any help with the Java wrapper would be appreciated though.

**Comment by jpsacha** [comment]
I looking into creating wrapper for CLandmark using JavaCPP. I created the [one](https://github.com/bytedeco/javacpp-presets/tree/master/flandmark) for FLandmark. Though I would net want to duplicate a similar effort if it is underway. We should coordinate it. Let me know if you have some plan how that Java interface for CLandmark should look like.

**Comment by henriquem** [comment]
Thks @jpsacha 

@uricamic please, help us at issues !

**Comment by uricamic** [comment]
Hi @jpsacha, 

I haven't started with Java interface yet, so if you want, you can start by yourself. My plan was to keep it simple and in the same spirit as the MATLAB and Python interface. I am not sure what are the requirements of possible users, I guess just the detector is enough (i.e. no interface for the learning).
