### ISSUE TITLE
Question on the green box

### ISSUE THREAD

**Issue by bettyyy** [uricamic/clandmark#43]
Hi! I am currently working your wonderful face detection program.
I want to ask how can I get/draw the green box as stated in the below screen capture?
![image](https://cloud.githubusercontent.com/assets/17765156/13671229/a1599eca-e709-11e5-8ed0-4993fa33dbee.png)

Thank you very much for answering! It will mean a lot to me!

**Comment by uricamic** [comment]
Hi @bettyyy, 

the green box is constructed from the response of C-DPM within C2F-DPM detector. Check the helper function in C2F-DPM [code snippets](http://cmp.felk.cvut.cz/~uricamic/clandmark/index.php?page=snippets#snippets_C2F-DPM_helpers_cpp) - there is a function `getUpdatedBBOX` which returns the corrected face box (green box in the image). It has the same format as the expected face box on input.

**Comment by bettyyy** [comment]
Thank you for your quick response! I will have a look on it and try to do it!

**Comment by bettyyy** [comment]
Dear uricamic,

May I ask what exactly the void function getUpdatedBBOX does? It seems that I cannot make it returns the corrected face box (green box in the image). 

Thank you very much!

**Comment by uricamic** [comment]
Hi @bettyyy, 

`getUpdatedBBOX` takes landmarks from the C-DPM detector and returns the corrected face box. The corrected box is calculated from landmarks as follows - the in-plane rotation is calculated as the deviation of least squares best line fitted to landmarks corresponding to eyes from the x-axis. The center of the corrected box is put on the centeroid of all landmarks and the size is computed based on the distance of centeroid of both eyes. 

It works best for the near-frontal face orientations, it gets worse when the face is close to profile pose.
