### ISSUE TITLE
build error in VS under windows

### ISSUE THREAD

**Issue by meirela** [uricamic/clandmark#47]
Hey, I'm following the windows installation guide by screen shots 
([http://cmp.felk.cvut.cz/~uricamic/clandmark/index.php?page=installation#install_windows](url))
And I've come to a stage where I tried and compile the VS project solution, after a (not so easy but) successful CMake configuration and generation. Now, when trying to build flandmark (or ALL_BUILD) I get:
![clandmark](https://cloud.githubusercontent.com/assets/12196398/14315069/d5c4f574-fc03-11e5-802e-de1eb293119a.JPG)

Both, for release and debug builds.
And indeed, I can't find the clanmark.lib file anywhere...

Again - CMake is done successfully, I am using Win7 64 bit VS2013 (VS12) CMake 3.0.2.

**Comment by meirela** [comment]
Sorry, for some reason (lack of sleep, I assume...) I didn't see [https://github.com/uricamic/clandmark/issues/46](url) which helped me exactly with this problem.

**Comment by uricamic** [comment]
Hi @meirela, 

and what about `clandmark.dll`, do you see it somewhere within your build folder? If yes, then the problem is probably that you have `BUILD_SHARED_LIBS` set to `ON`. When you set it to `OFF` and recompile, you shoud get .lib files as well.

**Comment by meirela** [comment]
Yep, that did the trick...

**Comment by uricamic** [comment]
Nevermind, it is always better to have duplicity in solved problems, so it is easier for others to find the answer ;-)
