### ISSUE TITLE
clandmark vs flandmark

### ISSUE THREAD

**Issue by vinnitu** [uricamic/clandmark#5]
As I understand clandmark is new version of library.
But I saw usage flandmark in the same time with clandmark (static_input.cpp)
Why? Can we use only lastest version of clandmark?

**Comment by uricamic** [comment]
Hi, 

yes, CLanmark serves as a full replacement of flandmark. However, it is a general library, which can be used also for different problems than just facial landmark detection. 
The enclosed examples are inherited from the flandmark library. New examples (e.g. the multi-view facial landmark detector) will be published soon.

**Comment by vinnitu** [comment]
Ok, thx.
I am waiting for.
