### ISSUE TITLE
Matlab example - Undefined function 'create_xml_init' for input arguments of type 'cell'.

### ISSUE THREAD

**Issue by botev** [uricamic/clandmark#52]
When I try to run `createModelFor300W` I get the error that there is no such function create_xml_init. Am I missing something?

**Comment by uricamic** [comment]
Hi @Botev, 

thank you for noticing, it seems I forgot to include it in the commit. I will fix this soon.

**Comment by uricamic** [comment]
Should be fixed now, the `create_xml_init.m` function is in `matlab_interface/functions/` folder.

**Comment by botev** [comment]
Thanks for that a lot! Now I think it works, however can you post a link to the 300W dataset in the format that CLandmark is using? The current links I get from google http://ibug.doc.ic.ac.uk/resources/300-W/ are broken. 

PS: Also if it might be possible to write a scirpt or have some comments on how to run one of the pretrained models on new images, that would be great.

**Comment by uricamic** [comment]
Hi @Botev, 

I will describe the format of the `.mat` file describing the database soon. However, I cannot provide the images, for those, you have to ask the people from the i-bug group. 

To run the pretrained models on new images all you need to do is to detect the face (e.g. using the OpenCV face detector) and then call the detect function from the `CLandmark` class, see [the MATLAB example](https://github.com/uricamic/clandmark/blob/master/matlab_interface/flandmark_simple_example.m), where the face detections are loaded from a file. 
I have also added MATLAB functions calling some specific versions of the detector, e.g. the [C2F-DPM](https://github.com/uricamic/clandmark/blob/master/matlab_interface/functions/c2f_dpm.m) and you can check the new `simple_example.m` which calls it.
