### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by punkhooren** [uricamic/clandmark#56]
My OS is Ubuntu 14.04 LTS, OpenCV 2.4.11, CMake 3.5
 ./video_input ./ flandmark_model.xml cam 0                                                  10:01:06 
It's OK. But when I want save the result.
 ./video_input ./ flandmark_model.xml cam 0 output.avi                                  10:02:01 
HIGHGUI ERROR: V4L2: Unable to get property <unknown property string>(5) - Invalid argument
OpenCV Error: Unspecified error (GStreamer: cannot link elements
) in CvVideoWriter_GStreamer::open, file /home/ren/Compile/OpenCV/opencv-2.4.11/modules/highgui/src/cap_gstreamer.cpp, line 1396
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/ren/Compile/OpenCV/opencv-2.4.11/modules/highgui/src/cap_gstreamer.cpp:1396: error: (-2) GStreamer: cannot link elements
 in function CvVideoWriter_GStreamer::open

[1]    19794 abort (core dumped)  ./video_input ./ flandmark_model.xml cam 0 output.avi

**Comment by uricamic** [comment]
Hi @KeeganRen, 

I think I had similar error once and it was solved by upgrading the codecs. Unfortunately, I do not remember what versions I had and which versions solved the problem eventually. 

However, this is a problem related to OpenCV and not to CLandmark, so I recommend to ask on OpenCV sites.
