### ISSUE TITLE
Why the detected landmarks in the example "static_input" are not correct?

### ISSUE THREAD

**Issue by wguo68** [uricamic/clandmark#57]
![bad](https://cloud.githubusercontent.com/assets/4994038/16078419/6a09f3d8-3331-11e6-9ead-4448f37b20d6.jpg)

And is there any trained model to detect more landmarks as in your website?

**Comment by uricamic** [comment]
Hi, 

the reason is that `static_input` (unlike `video_input`) uses new mechanism of features computation (`CFeaturePool`), which makes the `flandmark_model.xml` incompatible. 

Sorry for the inconvenience, I will upload the new `flandmark_model.xml` compatible with `CFeaturePool` soon.

**Comment by uricamic** [comment]
I forgot to add, that you can of course still use `flandmark_model.xml`, but you have to remove `CFeaturePool` from the code (look at `video_input.cpp` example, which is using the old style).

Or you can use the new style, but with the other models available for download on the project webpage (like `CDPM.xml`, `FDPM.xml`, `jointmv*`, etc.).

**Comment by wguo68** [comment]
Where is the other trained models for download ? Is there 68 landmark trained model?

There is an compile error for the code line "!face_cascade.load( argv[1]+face_cascade_name ) " .I modified this line to "!face_cascade.load( argv[1]) "

**Comment by uricamic** [comment]
Hi @wguo68, 

the learned models are [here](http://cmp.felk.cvut.cz/~uricamic/clandmark/index.php?page=downloads#learned-models).

`CDPM.xml` and `FDPM.xml` are detecting 68 landmarks and they are supposed to be use together, forming the `C2F-DPM`, check the [code snippets](http://cmp.felk.cvut.cz/~uricamic/clandmark/index.php?page=snippets#snippets-C2F-DPM) for this kind of detector.

**Comment by wguo68** [comment]
It's Okay. Great!
![good](https://cloud.githubusercontent.com/assets/4994038/16082738/2798cb46-3345-11e6-9a13-253d33abec4e.jpg)

For  large image，it may not be correct enough. How to improve the result for large image?

**Comment by uricamic** [comment]
Hi @wguo68, 

sorry for late answer, I didn't get notification for a new message in this thread. 

For larger image, there are several options what to do. If you would like to use only CLandmark, you could train a new model for a higher resolution images, however this would take a lot of time and resources. 
Other possible solution is to use CLandmark for initialization of some other technique which is more suitable for high resolution images (with large faces), like the Active Appearance Models (AAM) and related methods. These are known to have very good results for such images, however they usually suffer when the initialization is poor. The combination of CLandmark and AAM could provide fast, but still highly accurate detection.
