### ISSUE TITLE
compilation error in clandmark

### ISSUE THREAD

**Issue by mohanrajmit** [uricamic/clandmark#62]
i have compiled the clandmark library using camke. i have opened clandmark.sln file and compiled it's shows the following.
![image](https://cloud.githubusercontent.com/assets/9213878/17090770/752c0fbe-5251-11e6-8fa9-17f69cb44962.png)

kindly help to resolve the above mentioned error.

**Comment by uricamic** [comment]
Hi @mohanrajmit, 

all error which you have encountered should be solved by following the advice from the issue #46. If you have any problems or something in that thread is not clear, just ask.

**Comment by mohanrajmit** [comment]
i have compiled by setting dlib shared library and build cpp examples are false.  now am not getting any errors. two files are created fladmark.lib and clandmark.lib.

**Comment by mohanrajmit** [comment]
am not able to get dll files and while compiling cpp examples am getting errors.
kindly help me to resolve the errors.

**Comment by uricamic** [comment]
Hi @mohanrajmit, 

to get the `.dll` files you have to switch the `BUILD_SHARED_LIBS` to `ON` and compile again. I am sorry for this inconvenience, on Linux and Mac, this works more intuitively.

**Comment by mohanrajmit** [comment]
now i had set BUILD_SHARED_LIBS to true. only clandmark.dll is created.
![image](https://cloud.githubusercontent.com/assets/9213878/17099981/52d80c5a-5289-11e6-9586-5ee93b19fdbe.png)

after that am getting following errors

**Comment by uricamic** [comment]
Hi @mohanrajmit, 

I do not understand this, in previous message, you said that you got both `flandmark.lib` and `clandmark.lib` and now it seems that `clandmark.lib` is missing. Have you compiled it in `Release` mode with `BUILD_SHARED_LIBS=OFF` previously as well? I mean if it was generated once, it should still be there...

**Comment by mohanrajmit** [comment]
i regenerated the solution file by enabling BUILD_SHARED_LIBS true by using cmake. after compiling this solution lib files are not there.

**Comment by uricamic** [comment]
What version of Visual Studio are you using?

**Comment by mohanrajmit** [comment]
visual studio 2012

**Comment by uricamic** [comment]
That's weird. I was also using this version, and it was not removing the files in my case. Nevermind, please try to copy the generated `.lib` files somewhere else and then copy them back for the compilation of `.dll` files.

**Comment by mohanrajmit** [comment]
i have one question, after enabling BUILD_SHARED_LIBS to true , i have click configure and then generate or directly i have to press generate.

**Comment by uricamic** [comment]
I guess you have to configure first. Otherwise, it should generate the last valid configuration.

**Comment by mohanrajmit** [comment]
thanks alot. now i copied and pasted it.
![image](https://cloud.githubusercontent.com/assets/9213878/17100572/d2956174-528c-11e6-8963-f22d04e8696f.png)
now i got both dll and lib

**Comment by uricamic** [comment]
Glad to hear that :) So, now everything works for you?

**Comment by mohanrajmit** [comment]
now am trying to compile the example file. am regenerating the solution file for example

**Comment by uricamic** [comment]
Ok

**Comment by mohanrajmit** [comment]
now i compiled example also. exe are created . where i can get cpdm.xml .

**Comment by mohanrajmit** [comment]
to run the static input and video input exe files

**Comment by uricamic** [comment]
Hi, all available models are [here](http://cmp.felk.cvut.cz/~uricamic/clandmark/index.php?page=downloads#learned-models).

**Comment by mohanrajmit** [comment]
am getting following error while static_input.exe file
![image](https://cloud.githubusercontent.com/assets/9213878/17101016/b636a346-528f-11e6-9a4b-c8369e25afae.png)

**Comment by uricamic** [comment]
that means that the path to haar_cascade is incorrect. It is supposed to be given only as a path containing the `.xml` file and it has to end by `\`. Sorry fo that, it is not written specifically.

**Comment by mohanrajmit** [comment]
now its working fine. again thanks alot for patient answering all questions.

![image](https://cloud.githubusercontent.com/assets/9213878/17101225/fc443370-5290-11e6-96eb-35e78ef53170.png)

it looks like flandmark model.

**Comment by mohanrajmit** [comment]
The following model present in folder.
![image](https://cloud.githubusercontent.com/assets/9213878/17101268/43a9b780-5291-11e6-911a-cc7c6223b323.png)
where i can get Joint Multi-view Facial Landmarks Detector and Coarse-to-fine (C2F-DPM) dense landmark set detector model.

**Comment by uricamic** [comment]
Hi,

no problem. 

I should just warn you that this old `flandmark_model.xml` model file is not compatible with this `static_input` example. Since the example code uses new way of computing features, which is faster. I haven't released the compatible version for these 8 landmarks yet. This is also described in several threads here. So, please use e.g. `cdpm.xml` or `jointmv_frontal.mv` with this code example.

**Comment by uricamic** [comment]
they are also available for download on the project [webpage](http://cmp.felk.cvut.cz/~uricamic/clandmark/index.php?page=downloads#learned-models)

**Comment by mohanrajmit** [comment]
thanks for the whole support. now am able to use clandmark library.
![image](https://cloud.githubusercontent.com/assets/9213878/17101712/a01a737c-5293-11e6-96b4-44228b4ae1ba.png)

**Comment by uricamic** [comment]
Glad to hear that :), you are welcome. 

Final remark, the best results for this dense 68 landmark set are obtained by combining both `C-DPM` and `F-DPM` models, forming the `C2F-DPM` as described in our IMAVIS paper and available also in the code snippets on the project web page.

**Comment by SebasRode** [comment]
Hi, I have success to compile the library. Now I want to integrated in a particular project mine. I copied the same configuration from "video_input" project. But when I try to compile I have next issue:

![image](https://cloud.githubusercontent.com/assets/26137882/23503085/68c4f57e-ff3a-11e6-8373-35480108a63d.png)

Anyone can help me?
Thanks!
