### ISSUE TITLE
missing -lopencv_imgcodecs for libopencv 3.1.0

### ISSUE THREAD

**Issue by mousomer** [uricamic/clandmark#73]
On libopencv 3.1 they moved some functions from highgui to imagecodecs, so the build system should have **-lopencv_imgcodecs** and **-lopencv_videoio** added when linking the examples.

Unfortunately,  I'm not verse enough in cmake to make that change myself.

**Comment by uricamic** [comment]
Hi @mousomer, 

thank you for pointing this out. I am working on the new build scripts, so I can add this there. It will take me some time though, so if you need some quick patch, simply add  `imgcodecs videoio` to this line: https://github.com/uricamic/clandmark/blob/master/examples/CMakeLists.txt#L3 in `CMakeLists.txt` configuration file for buidling the `C++` examples. 
 It should work without problems, unless they changed the `FindOpencv.cmake`  script dramatically.

**Comment by uricamic** [comment]
I am closing this. Feel free to re-open if some further problems appear.

**Comment by mousomer** [comment]
Thanks. I've done the build from command-line.
