### ISSUE TITLE
Ask some questions for using "C2F-DPM.xml"

### ISSUE THREAD

**Issue by happygao** [uricamic/clandmark#81]
Hi,
   I want to use the "C2F-DPM.xml" to deal with videos by using C++, I download the code from your website,but the code snippets do not show the function of getUpdatedBBOX(). could you give me the code of function please, thankyou very much.

**Comment by happygao** [comment]
@uricamic

**Comment by uricamic** [comment]
Hi @happygao, 

actually, the code snippets contain this function, it is just hidden on the [other tab](http://cmp.felk.cvut.cz/~uricamic/clandmark/index.php?page=snippets#snippets_C2F-DPM_helpers_cpp).

**Comment by happygao** [comment]
Hi,@uricamic
    Thank you very much.I find the function of getUpdatedBBox(). 
    I use the C2F-DPM to deal with the video datas. The speed is so slow of fps:1.8. And the result is terrible. The result of your website is so good, I can not find the question of code. Is it has something with the video datas? Could you help me answer it?

**Comment by uricamic** [comment]
Hi @happygao 
I responded to your email.  The fps should be around 10 fps (depending on your hardware) for the C2F-DPM model. This holds for video with a single face and the face detection time is not counted. Please provide me some exemplary frames from the video on which you obtain these bad results, so I can give you some hints what might be wrong.

**Comment by happygao** [comment]
OK,thank you for your help. I clean up my code and the bad examples,then send the email to you.
