### ISSUE TITLE
Can I use this lib to detect smile ?

### ISSUE THREAD

**Issue by matakk** [uricamic/clandmark#84]
Thanks you!
I need detect smile on face. I have test the static_input.exe with CDPM.xml FDPM.xml model . 
but I can‘t find howto get mouth point on landmark points .

**Comment by uricamic** [comment]
Hi @matakk, 

check Figure 3. in this paper: http://cmp.felk.cvut.cz/ftp/articles/uricar/Uricar_ICCVw_2015.pdf for the IDs of mouth landmarks. Both CDPM and FDPM models have the same numbering. 
Keep in mind that the IDs in the figure are 1-based.

**Comment by uricamic** [comment]
Closing this since no other reaction appeared
